import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import {cn} from "@/lib/utils";
import {getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";
import {ThemeProvider} from "@/components/theme/theme-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                       params: {locale}
}: Readonly<{
    children: React.ReactNode;
    params: {locale: string};
}>) {
    const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
      )}>
          <ThemeProvider attribute={"class"} defaultTheme={"dark"} enableSystem disableTransitionOnChange>
            <NextIntlClientProvider messages={messages}>
                {children}
            </NextIntlClientProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
